### ISSUE TITLE
Cannot init DB on MySQL (sch_usr_notification)

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#425] opened 2015-06-23 19:23 UTC
When executing data-core.sql
The insert command does not match the table schema, which has 6 columns.
```
0	168	21:21:03	INSERT INTO `sch_usr_notification` VALUES (NULL,1,1,1),(NULL,2,1,1)	Error Code: 1136. Column count doesn't match value count at row 1	0.031 sec
```

**Comment by jakubklimek** [comment] 2015-06-23 19:40
Works when I add 1,1 and I presume that is the correct setting

**Comment by skrchnavy** [comment] 2015-06-24 06:00
@eea03 is this related to #419 ?

**Comment by eea03** [comment] 2015-06-24 07:16
Seems this was caused by incorrect merge of #419 and changes in develop merged by #417. 
Fixed, tested.

**Comment by tomas-knap** [comment] 2015-06-24 07:40
@jakubklimek Please check it is ok now

**Closed** 2015-07-17 08:15 UTC
Labels: priority: High, resolution: fixed, severity: bug, status: resolved
