### ISSUE TITLE
Feature request: delete pipeline executions

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#362] opened 2015-04-22 05:19 UTC
Currently (791cdce39008b4553e068ba1e2f42a90b7001164), there's no way how to delete individual pipeline executions other than directly removing files from `general.workingdir` and rows from database. Intermediate data produced by pipelines thus keeps on piling and takes up valuable disk space.

One possible solution would be to add a "delete" button to each row in the list of pipeline executions in the Execution monitor.

**Comment by tomas-knap** [comment] 2015-05-25 10:18
When pipeline execution is deleted, it is necessary to: 
1) delete all information related to the execution from DB  from `exec_*` tables
| exec_context_dpu           |
| exec_context_pipeline      |
| exec_dataunit_info         |
| exec_pipeline              |
| exec_record    |

2) delete all information related to the execution from `general.workingdir`, which removes temporary files, configurations etc. related to pipeline executions
3) delete logs - table `logging` in DB
4) delete debug data from working rdf store (Virtuoso/Sesame) - for local RDF this does not bring any extra effort as the working data are removed in 2)

Note: Logs which are logged to frontend/backend.log or frontend_error/backend_error can be managed by setting up how long they should be kept in config.propertes (`backend.log.keepDays`).

Proposed solution: 
In UnifiedViews GUI, in Menu->Settings, there should be new item - "Manage debug and working data", which should provide a possibility for admin to manually clean up debug and working data specified in points 1) - 4) above. Admin may specify that pipeline execution data older than X days should be removed. Data are removed after clicking on button "Delete". The operation is executed on background and when done, Status is updated. See below:

![screen shot 2015-05-25 at 12 13 19](https://cloud.githubusercontent.com/assets/3014917/7795681/75deb698-02d7-11e5-842e-3b51224e46aa.png)
 

See also: https://utopia.sk/wiki/display/ODN/sto_94%3A+Delete+pipeline+execution+data


Note: Feature of manually cleansing debug data was in the previous versions of UV and it is necessary so that it is ensured that working database does not become slower and slower as the time goes.

**Comment by skrchnavy** [comment] 2015-06-02 15:25
@tomas-knap what is scope of this task? Based on https://github.com/UnifiedViews/Core/issues/362#issuecomment-105198649 it is not clear what shall be implemented here and what belongs to other tasks.

**Comment by tomas-knap** [comment] 2015-06-18 09:32
1-3 steps as described above belong to this task

**Comment by tomas-knap** [comment] 2015-08-06 10:59
Please improve the resulting message, so that it shows how many executions was pruned. Now, there is just: 

<img width="414" alt="screen shot 2015-08-06 at 12 58 22" src="https://cloud.githubusercontent.com/assets/3014917/9110060/ecae14fc-3c3a-11e5-87f5-e5d28b4b065b.png">

**Comment by tomas-knap** [comment] 2015-08-06 11:03
When I specify something meaningless as the "number of days" e.g.: 

<img width="450" alt="screen shot 2015-08-06 at 13 00 41" src="https://cloud.githubusercontent.com/assets/3014917/9110110/36ef13c2-3c3b-11e5-84c8-fee55c6b48f2.png">

It does something - it writes "running", "done", but it is not clear what it actually does. 
Solution: In case of invalid input (it is not a number 0+), there should be error message displayed to the user, that valid values are... and no prunning should occur.

**Comment by tomas-knap** [comment] 2015-08-06 11:42
Bug I encountered:

1) Run one pipeline in debug mode. Go to Settings -> Manage debug and working data, specify 0 to the text field, click "Delete"
2) As a result all pipeline executions run in debug mode are deleted. 
3) Click on Execution Monitor menu item, you got: 

<img width="1280" alt="screen shot 2015-08-06 at 13 40 52" src="https://cloud.githubusercontent.com/assets/3014917/9110786/cbff2538-3c40-11e5-9dbe-20ed030ef8eb.png">

In the log, there is: 
```
13:10:06.568 [http-bio-8080-exec-5] TRACE c.c.m.x.o.f.d.c.d.DbCachedSource - ExecutionViewAccessor.getObjectByIndex(0) -> loaded
13:10:06.568 [http-bio-8080-exec-5] DEBUG c.c.m.x.o.f.g.v.e.ExecutionListPresenterImpl - ExecutionMonitor refreshed.
13:10:06.569 [http-bio-8080-exec-5] DEBUG o.e.p.logging.sql - 2015-08-06 13:10:06.569--ServerSession(812391448)--Connection(1411116334)--SELECT ID, t_end, debug_mode, t_last_change, order_number, silent_mode, t_start, STATUS, stop, user_actor_id, debugnode_id, owner_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (ID = ?)
	bind => [8]
13:10:06.570 [http-bio-8080-exec-5] DEBUG c.c.m.x.o.f.g.c.DebuggingView - Tables refresh start
13:10:06.571 [http-bio-8080-exec-5] ERROR c.c.m.x.o.f.AppEntry - Uncaught exception
java.lang.NullPointerException: null
	at cz.cuni.mff.xrg.odcs.frontend.gui.tables.LogTable.isRunning(LogTable.java:254) ~[LogTable.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.tables.LogTable.refresh(LogTable.java:292) ~[LogTable.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.fillContent(DebuggingView.java:303) ~[DebuggingView.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.refresh(DebuggingView.java:330) ~[DebuggingView.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.restore(DebuggingView.java:397) ~[DebuggingView.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListViewImpl.enter(ExecutionListViewImpl.java:110) ~[ExecutionListViewImpl.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionlist.ExecutionListPresenterImpl.enter(ExecutionListPresenterImpl.java:98) ~[ExecutionListPresenterImpl.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.navigation.PresenterWrap.enterPresenter(PresenterWrap.java:41) ~[PresenterWrap.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.navigation.PresenterViewDisplay.showView(PresenterViewDisplay.java:46) ~[PresenterViewDisplay.class:na]
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:575) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:527) ~[vaadin-server-7.3.7.jar:7.3.7]
	at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorImpl.navigateTo(ClassNavigatorImpl.java:60) ~[ClassNavigatorImpl.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorHolder.navigateTo(ClassNavigatorHolder.java:22) ~[ClassNavigatorHolder.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.MenuLayout$NavigateToCommand.menuSelected(MenuLayout.java:362) ~[MenuLayout$NavigateToCommand.class:na]
	at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:191) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:485) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:301) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.7.jar:7.3.7]
	at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:102) [ODCSApplicationServlet.class:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.39]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.39]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.39]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.39]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.39]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009) [tomcat-coyote.jar:7.0.39]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.39]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.39]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
13:10:06.573 [http-bio-8080-exec-5] INFO  c.c.m.x.o.f.ODCSApplicationServlet - Request (457) finished processing in: 18 ms
13:10:06.573 [http-bio-8080-exec-5] DEBUG c.c.m.x.o.f.ODCSApplicationServlet - Request (/unifiedviews/UIDL/) URI
13:10:08.881 [http-bio-8080-exec-5] INFO  c.c.m.x.o.f.ODCSApplicationServlet - Request (458) received

```

If you click once again on Execution Monitor menu item, it works correctly. 

Problem: After deleting pipeline executions, something in Exec monitor is not properly initialized.

**Comment by tomas-knap** [comment] 2015-08-06 11:46
When I come to Settings -> Managed debug and working data, please pre-fill the text box "number of days" (see below) to contain reasonable default value, e.g., "10"

<img width="837" alt="screen shot 2015-08-06 at 13 45 47" src="https://cloud.githubusercontent.com/assets/3014917/9110853/769852da-3c41-11e5-95c1-7cb619240302.png">

**Comment by tomas-knap** [comment] 2015-08-06 11:50
If can be done quickly - please add some spaces around the textbox "number of days" below: 

<img width="837" alt="screen shot 2015-08-06 at 13 45 47" src="https://cloud.githubusercontent.com/assets/3014917/9110900/d24793ca-3c41-11e5-80b7-69d2afb64586.png">

**Comment by mkl-eea-sk** [comment] 2015-08-06 11:52
For text box prefill, maybe I would recommend using 
https://github.com/UnifiedViews/Plugins/blob/feature/resolve%23241/e-sparqlEndpoint/src/main/java/eu/unifiedviews/plugins/extractor/sparqlendpoint/SparqlEndpointVaadinDialog.java#L103-L131 
ComboBox with new values enabled.
It gives a chance for unexperienced user to just select the value, and 
still it is editable (and disallows non-integral values).

**Comment by tomas-knap** [comment] 2015-08-06 11:53
Yes, that is possible

**Comment by tomas-knap** [comment] 2015-08-06 11:53
Changes should be put to pull request https://github.com/UnifiedViews/Core/pull/443

**Comment by eea03** [comment] 2015-08-12 11:00
NullPointerException fixed in https://github.com/UnifiedViews/Core/commit/c9c79c379a68fee159524d3391e48132a81a0150

Actually the bug was caused by remnants of old implementation where execution displayed in monitor was preserved between tabs switches.
Should work as expected now, I tested it and it was OK

**Comment by eea03** [comment] 2015-08-12 11:08
I have encountered an issue during testing. Status line is displaying 2times more deleted entries that actually was deleted.
When I have 2 executions, status says 4 entries were deleted.
When I have 3 executions, status says 6 entries were deleted.
I would expect status informs how many executions were deleted. Or does it have some other meaning?

Example where I had 3 pipeline executions and they were all deleted:
```
Stav: Hotovo (2015-08-12 13:04:05) Počet vymazaných záznamov: 6
```

**Comment by mbl-eea-sk** [comment] 2015-08-12 11:14
I have tested this up to 5 executions (including debugged) and in each case the message was displayed correctly...

**Comment by eea03** [comment] 2015-08-12 11:36
Strange, for me it's every time ... I have tried 2,3,4,5,6 executions and I always get x2 deleted entries, no matter they are debugged, non-debugged or mix of these two.
Maybe someone else could test this and we'll see if it is an issue or just some strange behavior on my instance

**Comment by tomas-knap** [comment] 2015-08-14 16:14
Lets close this issue now, because pull request with the feature was already merged. The issue discussed above is specified in a separate issue: https://github.com/UnifiedViews/Core/issues/501

**Closed by tomas-knap** 2015-08-14 16:14 UTC
Labels: priority: High, severity: enhancement, status: ready for test
