### ISSUE TITLE
Blank pipeline run ends with FAILED status without any error message

### ISSUE THREAD

**Issue by eea03** [UnifiedViews/Core#410] opened 2015-06-10 14:05 UTC
When blank pipeline is saved and run, it ends with FAILED status but no error message explaining the reason is displayed;
This is very confusing; 
I would expect it to fail with message that no DPU found to execute;

Another possibility would be mark pipeline status as WARNING and give proper message that pipeline has no DPUs

Motivation:
- this bug was discovered when updating DPUs via UV master API.
- all DPU instances were deleted, so blank pipelines remained (also a bug, but still can happen something like this)
- pipelines started to fail without any error message

**Comment by mkl-eea-sk** [comment] 2015-07-07 14:21
Lets define "blank pipeline". From first 4 paragraphs, I understood that blank pipeline is:
1. Create pipeline
2. name it
3. save and close (no DPU added on canvas)

But from
> all DPU instances were deleted, so blank pipelines remained (also a bug, but still can 
> happen something like this)
it seems that you report a bug against illegal situation. What does it mean 'DPU deleted', if they are present in pipeline graph but not in dpu_templates... it is DB inconsistency (we should add foreign key if there is not). Reporting but against illegal state of application is crazy. Lets assure this inconsistency cannot happen.

So which of these two is this bug about? And if it is the latter one - please provide me with steps to reproduce (and will fix the cause bug - the one causing inconsistencies)

**Comment by eea03** [comment] 2015-07-07 14:37
The bug is that blank pipeline should not run and end with FAILED status without any explanation. I think that blank pipeline should not be able to run at all.
Maybe it would not be possible to save blank pipeline

Blank pipeline is exactly as you described.
I just described another case we ended up with blank pipelines (DPU templates were deleted from database, so cascaded all DPU instances were deleted too)

**Comment by skrchnavy** [comment] 2015-07-07 21:20
pipeline without dpu and also pipeline without extractor or loader shall be visually marked as invalid in list of pipelines and only edit of such pipeline shall be possible. No scheduled run on such pipeline.

**Comment by mkl-eea-sk** [comment] 2015-07-08 06:09
@tomas-knap should pipeline without any DPU be even possible to exist?
@skrchnavy please, do not mix this bug issue with enhancement, if you 
need frontend enhancement to distinguish pipelines by having or not 
havind extractors/loaders, create another issue. and why you think such 
pipeline is invalid... @tomas-knap - is pipeline without 
loaders/extractor, only with transformers, considered invalid in some way?

**Comment by skrchnavy** [comment] 2015-07-08 12:11
@mkl-eea-sk How will end up pipeline with no extractor nor loader? Probably finishes without any error message but no data are produced. So for me same issue as blank pipeline.

**Comment by mkl-eea-sk** [comment] 2015-07-13 12:29
I have added validation on service level (PipelineFacade.save), on GUI with neat message. In backend execution - failure event is added to event log to explain fail reason.
This fixes original bug, not the extensions @skrchnavy  described, as these are not well elaborated requirements - if desirable, open new issue with new feature requirements.

**Comment by skrchnavy** [comment] 2015-07-16 14:28
This implementation as discussed could be problem in ODN whe pipeline created via master API. Proposed is to display warning that empty pipeline is to be saved and could cause issues.
Also I see it better to avoid start of such pipeline with error message that pipeline is without DPU so no correct output produced.

**Comment by tomas-knap** [comment] 2015-07-20 09:25
I agree with validation on empty pipeline during pipeline execution and with special event being reported. But during pipeline design, creating empty pipeline is ok and it should be possible to save the pipeline with no DPUs.

**Closed** 2015-08-06 05:28 UTC
Labels: priority: High, severity: bug
