### ISSUE TITLE
Frontend: Communication error and then cannot connect from the same session

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#165] opened 2014-09-09 12:37 UTC
Sometimes frontend says "Communication problem" and then it is not possible to connect from the same browser. It is however possible to connect from a different browser or using "incognito" window. So this is probably some problem with sessions.

**Comment by jindrichmynarz** [comment] 2015-02-24 12:35
As @jakubklimek indicates, it seems that the front-end of UnifiedViews doesn't handle sessions correctly. I use UnifiedViews from the develop branch, commit 4ed9b6172c3547924753de3e45621cce7332c327. When I log in to the front-end, go to edit a pipeline, then I open the home page (i.e., <http://localhost:8080/unifiedviews/>) in a different tab of the same browser, then the tab with an edited pipeline logs out automatically (potentially losing unsaved changes). This doesn't happen when I open the home page in an incognito tab or a different browser, suggesting it's indeed a problem with sessions. Are sessions reset when user arrives at the home page?

**Comment by tomas-knap** [comment] 2015-04-27 08:39
@jindrichmynarz Can you please retest if you still experience the issue? I cannot reproduce on localhost

**Comment by jindrichmynarz** [comment] 2015-04-27 10:25
Using 791cdce39008b4553e068ba1e2f42a90b7001164 this issue is no longer reproducible.

**Comment by jindrichmynarz** [comment] 2015-04-27 13:36
I find a way to reproduce this issue with 791cdce39008b4553e068ba1e2f42a90b7001164. The difference is subtle that I assumed this is no longer an issue.

Steps to reproduce:

1. Open a pipeline for editing.
2. In another tab, go to <http://localhost:8080/unifiedviews> (note that there's no trailing slash)

You will be redirected to login (`/unifiedviews/#!Login`) and the opened pipeline will report "Communication problem", log you out and redirect to login.

If you open a pipeline for editing and go to <http://localhost:8080/unifiedviews/>, then this issue doesn't occur.

It seems that the issue is caused by the redirect from <http://localhost:8080/unifiedviews>.

**Comment by tomas-knap** [comment] 2015-04-30 09:33
Thanks Jindrich, planning the issue.

**Comment by mkl-eea-sk** [comment] 2015-08-07 11:06
This is unreproducible in UV_Core_2.1.2

**Comment by skrchnavy** [comment] 2015-08-07 12:53
Based on test it was reproducible in 2.1.0 and works OK in 2.1.2. So it was fixed as side efect of some another fix, closing as fixed in 2.1.2

**Closed by skrchnavy** 2015-08-07 12:53 UTC
Labels: priority: High, severity: bug, status: ready for test
