### ISSUE TITLE
DPU template is not deleted after copy and reconfigure

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Core#409] opened 2015-06-09 13:40 UTC
Steps to reproduce

* to copy DPU template
* to change configuration of copy, not saving changes
* To delete this changed DPU and to confirm deletion
 * _Result: DPU template disappears - CORRECT_
* To select another DPU template
* UV asks to save changes, to confirm save
 * _Result: DPU template is back - WRONG_

**Comment by tomas-knap** [comment] 2015-07-14 10:40
Cannot reproduce on develop be7554753fb1bb8cb4f0b624c135aeedea0294f6

It was probably solved by https://github.com/UnifiedViews/Core/commit/3385932b55ba744cd273f5f45d8e93a30cd7ea40

Closing, reopen if that re-appears

**Closed by tomas-knap** 2015-07-14 10:40 UTC
Labels: priority: High, severity: bug, status: planned
