### ISSUE TITLE
Cannot save DPU template in pipeline view using user's name

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#453] opened 2015-07-14 06:19 UTC
On a fresh install from latest master, I imported DPUs using "export DPU templates" from one instance and create templates from zip in the target instance. All the DPUs were created OK, with their default names. However, I also wanted to export/import T-VoidStatistics, which is a template of uv-t-sparqlConstruct. When I exported it, I was unable to import it - nothing happened, only message saying that I already have uv-t-sparqlConstruct. That is one issue. Then I decided to create that template manually, so that I can import my pipeline. So I created an empty pipeline, dragged uv-t-sparqlConstruct, configured it as T-VoidStatistics and saved as DPU template. However, instead of seeing this: 
![image](https://cloud.githubusercontent.com/assets/718827/8667475/b04c3026-2a00-11e5-8d14-bf768ee5ca3b.png)
I am seeing this:
![image](https://cloud.githubusercontent.com/assets/718827/8667435/27252cd0-2a00-11e5-82c5-4a535af3783f.png)
In the template configuration, the DPU template is named correctly and when I drag it on canvas, it is also named correctly. However, it is not named correctly in the DPU tree.

Nevertheless, I can import the pipeline then, so the issue is really in the naming of DPUs in DPU tree

**Comment by tomas-knap** [comment] 2015-07-14 09:07
Possible cause (the commit is already in master): https://github.com/UnifiedViews/Core/commit/6d05618a448ff464596eb4166b1a925fa8712f2d

**Comment by tomas-knap** [comment] 2015-07-14 09:10
Problem is in master branch, just retested.

**Comment by tomas-knap** [comment] 2015-07-14 09:12
Probably fixed by: https://github.com/UnifiedViews/Core/commit/6d05618a448ff464596eb4166b1a925fa8712f2d

**Comment by skrchnavy** [comment] 2015-07-14 09:13
could be related to #459

**Comment by eea02** [comment] 2015-07-14 09:16
I have just tried it on develop, and master, but I was unable to reproduce it.

**Comment by tomas-knap** [comment] 2015-07-14 09:17
On master, steps to reproduce: 
1) create pipeline
2) put e.g. t-sparqlUpdate on the pipeline
3) open t-sparqlUpdate, change name, save it "as new DPU template"
4) in the DPU tree, there is "t-sparqlUpdate" , but not the new name

**Comment by tomas-knap** [comment] 2015-07-14 09:40
Problem is also on the develop branch, the same steps to reproduce

**Comment by skrchnavy** [comment] 2015-07-14 09:44
It is possible to rename templatte in DPU Template screen. So title doesn't correctly describes situation

**Comment by tomas-knap** [comment] 2015-07-14 09:52
The problems seems to be with menu_name field in DB. 

If you follow the steps on reproduce above and then check database, the record (new DPU template) is there, "name" is properly set correctly to new name, but "menu_name" is not set properly - the original value remains there. And DPUTree displays the menu name.

**Comment by tomas-knap** [comment] 2015-07-14 10:00
One further observation. If you create new DPU template in DPU templates screen, you may adjust new names as you need (DPU Templates menu item, click on t-sparqlUpdate, click on "Copy", adjust name as you want). So the problem is somehow restricted only to DPUTree in PipelineEdit screen.

**Comment by jakubklimek** [comment] 2015-07-14 10:13
So it fills menu_name correctly then? Then it should be a bug in "Save as DPU template" functionality and import?

**Comment by eea02** [comment] 2015-07-14 10:35
I have retested it after fix, should work as expected now.

**Comment by skrchnavy** [comment] 2015-07-14 10:45
@eea02  Please test also if import from zip file correctly names DPUs (zip file with .lst about DPUs)

**Comment by eea02** [comment] 2015-07-14 11:55
I have fixed also import from zip file.

**Closed** 2015-07-14 12:06 UTC
Labels: priority: Urgent, severity: bug, status: in progress
