### ISSUE TITLE
Logs do not refresh properly sometimes

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#20] opened 2014-03-18 07:15 UTC
Not always, but often, logs stop to refresh.

This manifests in multiple ways.

1) Pipeline is long finished, but the rest of the logs is not visible:
![image](https://f.cloud.github.com/assets/718827/2445197/bf7a60f6-ae6c-11e3-9a1f-5d9f649ede68.png)
2) Pipeline is running, but the last log message is 15 minutes old. Even refreshing using F5 in web browser does not help. Looks like an issue with transactions? Maybe inserted logs are not committed and therefore visible to viewers?

**Comment by skrchnavy** [comment] 2015-01-22 15:22
@tomas-knap I suggest to close this issue (not touched for a long time) and create feature request with your proposal in above comment.

**Comment by tomas-knap** [comment] 2015-02-19 09:41
Cannot reproduce

**Closed by tomas-knap** 2015-02-19 09:41 UTC
Labels: priority: High, severity: bug
