### ISSUE TITLE
Failed to load DPU because of exception:org.osgi.framework.BundleException

### ISSUE THREAD

**Issue by skarampatakis** [UnifiedViews/Core#536] opened 2015-10-07 11:03 UTC
Hi all,
I have installed version 2.2.0 of Unified Views via github as described [here](https://grips.semantic-web.at/display/UDDOC/Installation+Guide) . I can actually access Unified Views from my local Tomcat7 Server, and have installed some plugins by uploading a zip file containing all the jars, but some of them fail to load as seen below. Any idea about how to tackle these problems would be helpful. 

plugin load errors:

 Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-e-sparqlEndpoint_1.1.0 [1]" could not be resolved. Reason: Missing Constraint: Import-Package: com.fasterxml.jackson.core; version="[2.4.0,3.0.0)"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-e-relationalFromSql_2.1.3 [2]" could not be resolved. Reason: Missing Constraint: Import-Package: org.osgi.service.jdbc; version="0.0.0"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-l-rdfToVirtuoso_1.0.3 [3]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-gzipper_1.0.3 [9]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-e-filesDownload_2.1.4 [13]" could not be resolved. Reason: Missing Constraint: Import-Package: com.jcraft.jsch; version="0.0.0"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-tabularToRelational_2.2.2 [14]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-sparqlSelect_2.1.4 [18]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-l-filesToParliament_1.0.3 [19]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-gunzipper_1.0.3 [20]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-rdfValidator_2.0.3 [22]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-tabular_2.3.0 [26]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.poi.hssf.usermodel; version="0.0.0"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-l-filesUpload_2.1.3 [28]" could not be resolved. Reason: Missing Constraint: Import-Package: com.jcraft.jsch; version="0.0.0"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-metadata_2.1.3 [29]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
* Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-filesFindAndReplace_2.1.3 [30]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"

unifiedviews/WEB-INF/lib

activation-1.1.jar
aopalliance-1.0.jar
asm-4.0.jar
asm-tree-4.0.jar
asm-util-4.0.jar
aspectjrt-1.7.3.jar
aspectjweaver-1.7.3.jar
atmosphere-runtime-2.1.2.vaadin6.jar
bcprov-jdk15-1.45.jar
cas-client-core-3.3.3.jar
cglib-3.0.jar
commonj.sdo-2.1.1.jar
commons-app-2.2.0.jar
commons-beanutils-1.8.3.jar
commons-cli-1.2.jar
commons-codec-1.10.jar
commons-collections-3.1.jar
commons-dbcp-1.4.jar
commons-dbcp2-2.0.1.jar
commons-digester-1.8.jar
commons-digester3-3.2.jar
commons-httpclient-3.1.jar
commons-io-2.4.jar
commons-lang-2.1.jar
commons-lang3-3.4.jar
commons-logging-1.1.1.jar
commons-pool-1.5.4.jar
commons-pool2-2.2.jar
commons-validator-1.4.0.jar
com.openlinksw.virtuoso.virtjdbc4_1-3.76-7-develop-20150303.232217-33.jar
com.openlinksw.virtuoso.virt_sesame2-1.21-7-develop-20150502.002807-20.jar
confirmdialog-2.1.3.jar
dataunit-2.2.0.jar
dataunit-file-2.2.0.jar
dataunit-file-impl-2.2.0.jar
dataunit-rdf-2.2.0.jar
dataunit-rdf-impl-2.2.0.jar
dataunit-relational-impl-2.2.0.jar
eclipselink-2.5.1.jar
esapi-2.0GA.jar
filteringtable-0.9.11.v7.jar
flute-1.3.0.gg2.jar
guava-16.0.1.vaadin1.jar
h2-1.4.182.jar
httpclient-4.4.jar
httpclient-cache-4.2.5.jar
httpcore-4.4.jar
jackson-annotations-2.3.0.jar
jackson-core-2.4.4.jar
jackson-databind-2.3.3.jar
jakarta-regexp-1.4.jar
jasypt-1.9.2.jar
javax.persistence-2.1.0.jar
jcip-annotations-1.0.jar
jcl-over-slf4j-1.7.7.jar
joda-time-1.6.2.jar
json-0.0.20080701.jar
jsonld-java-0.5.1.jar
jsoup-1.6.3.jar
jul-to-slf4j-1.6.1.jar
log4j-over-slf4j-1.6.1.jar
logback-classic-1.1.2.jar
logback-core-1.1.2.jar
lucene-core-3.5.0.jar
lucene-highlighter-3.5.0.jar
lucene-memory-3.5.0.jar
lucene-queries-3.5.0.jar
mail-1.4.jar
maven-artifact-3.3.3.jar
mysql-connector-java-5.1.6.jar
not-yet-commons-ssl-0.3.9.jar
opencsv-3.2.jar
opensaml-2.5.1-1.jar
openws-1.4.2-1.jar
org.eclipse.osgi-3.9.0.v20130305-2200.jar
plexus-utils-3.0.20.jar
popupbutton-2.4.1.jar
postgresql-9.3-1102-jdbc41.jar
refresher-1.2.1.7.jar
sac-1.3.jar
serializer-2.7.1.jar
sesame-config-2.8.1.jar
sesame-console-2.8.1.jar
sesame-http-client-2.8.1.jar
sesame-http-protocol-2.8.1.jar
sesame-model-2.8.1.jar
sesame-query-2.8.1.jar
sesame-queryalgebra-evaluation-2.8.1.jar
sesame-queryalgebra-model-2.8.1.jar
sesame-queryparser-api-2.8.1.jar
sesame-queryparser-serql-2.8.1.jar
sesame-queryparser-sparql-2.8.1.jar
sesame-queryresultio-api-2.8.1.jar
sesame-queryresultio-binary-2.8.1.jar
sesame-queryresultio-sparqljson-2.8.1.jar
sesame-queryresultio-sparqlxml-2.8.1.jar
sesame-queryresultio-text-2.8.1.jar
sesame-repository-api-2.8.1.jar
sesame-repository-contextaware-2.8.1.jar
sesame-repository-dataset-2.8.1.jar
sesame-repository-event-2.8.1.jar
sesame-repository-http-2.8.1.jar
sesame-repository-manager-2.8.1.jar
sesame-repository-sail-2.8.1.jar
sesame-repository-sparql-2.8.1.jar
sesame-rio-api-2.8.1.jar
sesame-rio-binary-2.8.1.jar
sesame-rio-datatypes-2.8.1.jar
sesame-rio-jsonld-2.8.1.jar
sesame-rio-languages-2.8.1.jar
sesame-rio-n3-2.8.1.jar
sesame-rio-nquads-2.8.1.jar
sesame-rio-ntriples-2.8.1.jar
sesame-rio-rdfjson-2.8.1.jar
sesame-rio-rdfxml-2.8.1.jar
sesame-rio-trig-2.8.1.jar
sesame-rio-trix-2.8.1.jar
sesame-rio-turtle-2.8.1.jar
sesame-runtime-2.8.1.jar
sesame-sail-api-2.8.1.jar
sesame-sail-federation-2.8.1.jar
sesame-sail-inferencer-2.8.1.jar
sesame-sail-lucenesail-2.8.1.jar
sesame-sail-memory-2.8.1.jar
sesame-sail-nativerdf-2.8.1.jar
sesame-sail-rdbms-2.8.1.jar
sesame-util-2.8.1.jar
slf4j-api-1.7.7.jar
spring-aop-3.1.2.RELEASE.jar
spring-asm-3.1.4.RELEASE.jar
spring-aspects-3.1.4.RELEASE.jar
spring-beans-3.1.4.RELEASE.jar
spring-context-3.1.4.RELEASE.jar
spring-context-support-3.1.4.RELEASE.jar
spring-core-3.1.4.RELEASE.jar
spring-expression-3.1.4.RELEASE.jar
spring-jdbc-3.1.2.RELEASE.jar
spring-orm-3.1.4.RELEASE.jar
spring-security-cas-3.1.4.RELEASE.jar
spring-security-config-3.1.4.RELEASE.jar
spring-security-core-3.1.4.RELEASE.jar
spring-security-web-3.1.4.RELEASE.jar
spring-tx-3.1.4.RELEASE.jar
spring-vaadin-integration-2.0.1.jar
spring-web-3.0.7.RELEASE.jar
streamhtmlparser-jsilver-0.0.10.vaadin1.jar
uv-dataunit-files-2.1.4.jar
uv-dataunit-helpers-2.1.4.jar
uv-dataunit-rdf-2.1.4.jar
uv-dataunit-relational-2.1.4.jar
uv-dpu-api-2.1.4.jar
uv-dpu-config-vaadin-2.1.4.jar
uv-dpu-helpers-2.1.4.jar
vaadin-client-compiled-7.3.7.jar
vaadin-lazyquerycontainer-2.0.9.jar
vaadin-push-7.3.7.jar
vaadin-sass-compiler-0.9.10.jar
vaadin-server-7.3.7.jar
vaadin-shared-7.3.7.jar
vaadin-slf4j-jdk14-1.6.1.jar
vaadin-themes-7.3.7.jar
velocity-1.5.jar
xalan-2.7.1.jar
xercesImpl-2.10.0.jar
xml-apis-1.4.01.jar
xmlpull-1.1.3.1.jar
xml-resolver-1.2.jar
xmlsec-1.4.4.jar
xmltooling-1.3.2-1.jar
xpp3_min-1.1.4c.jar
xstream-1.4.7.jar

module.path/dpu/

uv-e-distributionMetadata
uv-e-executeShellScript
uv-e-silkLinker
uv-l-filesToVirtuoso
uv-l-relationalToSql
uv-t-filesFilter
uv-t-filesMerger
uv-t-filesRenamer
uv-t-filesToRdf
uv-t-filterValidXml
uv-t-rdfGraphMerger
uv-t-rdfMerger
uv-t-rdfToFiles
uv-t-relational
uv-t-relationalToRdf
uv-t-sparqlConstruct
uv-t-sparqlUpdate
uv-t-unzipper
uv-t-xslt
uv-t-zipper

**Comment by tomas-knap** [comment] 2015-10-07 14:15
Hi, what is the content of folder ```lib```? The folder ```lib``` is a subfolder of the folder to which ```module.path``` config param from config.properties file points

**Comment by skarampatakis** [comment] 2015-10-07 14:27
Hi Tomas,
you mean config.properties of the file inside ```WEB-INF```, am I right. (because there are 2)
i have configured to be``` ~/unifiedviews/Core/backend/working``` so inside this directory there are two other folders ```dpu``` and ```temp``` but no ```lib```. The contents of ```dpu``` are shown above

**Comment by tomas-knap** [comment] 2015-10-07 14:51
So that it is the cause of your issues. The ```{module.path}/lib``` must contain libraries, which should appear in ```{Core}/target/lib``` after building the Core repository. 

Either please set ```module.path``` in both config.properties files to point to ```{Core}/target``` or copy content of ```{Core}/target/lib``` to ```{module.path}/lib```

I will update the installation guide to make it more clear.

**Comment by skarampatakis** [comment] 2015-10-07 15:57
my config.properties on ```backend/target``` are 
```module.path = /home/sotos/unified_views/Core/target```
and i changed config.properties on ```/var/lib/tomcat7/webapps/WEB-INF/``` as

```module.path = /home/sotos/unified_views/Core/target```

and restarted both backend and webapp, Now I am getting the following errors


*Failed to create DPUs directory: '0}'
...
about 30 times. I have changed permissions on Core/target but still the same response.

**Comment by tomas-knap** [comment] 2015-10-08 08:17
Can you please send the whole frontend.log/backend.log (from the moment you restart the application)? 

Under which user do you run frontend/backend? If it is not root or sotos, please doublecheck the permissions of ```/home/sotos/unified_views/Core/target```, I suggest you to precreate there ```dpu``` folder to check whether this solves the issue. 

What is the content of ```/home/sotos/unified_views/Core/target``` folder? There should be folder lib with all the shared libs from ```{Core}/target/lib```. Further there should be "dpu" folder where the dpus are loaded. You should load the DPUs via the administration interface of UnifiedViews.

**Comment by tomas-knap** [comment] 2015-10-08 08:18
If you have system which may install Deb packages, this is the preferred way how UnifiedViews should be installed and which should avoid these kinds of issues

**Comment by skarampatakis** [comment] 2015-10-08 12:18
I have managed to overcome the Core plugins installation by changing permissions to ```777``` in both ```{core}/target/lib``` and ```{core}/target/dpu```.

**Comment by jindrichmynarz** [comment] 2015-10-08 12:43
OK, so it was mainly an issue of insufficient documentation for installing UnifiedViews out of the source? Can we close the issue once @tomas-knap improves the documentation?

**Comment by Jan-Marcek** [comment] 2015-10-08 15:23
@skarampatakis Now, the Debian packages is for Debian Wheezy 7.

**Comment by skarampatakis** [comment] 2015-10-08 15:52
@Jan-Marcek So, do i need to set up a Debian Wheezy 7 distro in order to succesfully install it? 
I had a 12.04.5 Ubuntu which did some kind of installation but with errors. Tomcat is up and runnig mysql also but unified views is not working. Installation reported that could configure unifiedviews-backend-mysql and so another 3 modules could not installed correctly, as far as I understood. 

Currently my built from source local instance is up and working but i cannot install all of the plugins required for my work. Many of them are ok but some of them not. Also, gihub repo gives older versions than the one used in an example @jindrichmynarz sent to me, maybe need update? 

Also i have exported the DPUs as zip file from the example @jindrichmynarz sent to me, but trying to install them gives me errors, version errors probably of java 8 bulit components. So my question is if I update my java version to java 8 could I run these DPUs correctly? and the other that are currently working will be still working?

**Comment by jindrichmynarz** [comment] 2015-10-08 17:04
Some of the DPUs in the example I shared with you are from the [develop branch](https://github.com/UnifiedViews/Plugins/tree/develop). Additionally, there are few non-core DPUs from [this repository](https://github.com/mff-uk/DPUs). I believe most of these DPUs were compiled with Java 7, so Java version mismatch should not be the cause of your problem.

**Comment by tomas-knap** [comment] 2015-10-09 09:33
@skarampatakis, Regarding the issues of type: 

```
Failed to load DPU because of !unexpected! exception:cz/cuni/mff/xrg/uv/transformer/rdfandtemplatetofiles/RdfAndTemplateToFiles : Unsupported major.minor version 52.0
```

This is due to the fact that the DPU was built under Java8. So either you have to rebuild the DPU under Java 7 or you may rebuild whole UnifiedViews with Java8 profile (see the installation guide). I suggest you to start with the first approach - recompiling the DPUs you need. 

In general, all Plugins within https://github.com/UnifiedViews/Plugins should be available as artifacts in http://maven.eea.sk/artifactory/public/eu/unifiedviews/plugins/, where they should be bundled using Java 7. If not, it is an error. 


Regarding these types of issues: 

```
Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-zipper_1.6.0.SNAPSHOT [120]" could not be resolved. Reason: Missing Constraint: Import-Package: eu.unifiedviews.dataunit; version="[1.2.0,2.0.0)"
```
This is caused by using DPUs, which were build for UnifiedViews 1.X version. To ensure they also work in UnifiedViews 2.x environment, please read: https://grips.semantic-web.at/pages/viewpage.action?pageId=59113485

**Comment by tomas-knap** [comment] 2015-10-09 09:38
@skarampatakis, regarding the versions of DPUs, using those from master branch from https://github.com/UnifiedViews/Plugins should work and should have up to date version. If not, this is a bug.

**Comment by tomas-knap** [comment] 2015-10-09 09:39
@skarampatakis Regarding Java8 plugin, if you want to use those, you have to "mvn clean install" the UV Core with Java8 profile - see: https://grips.semantic-web.at/display/UDDOC/Installation+Guide

**Comment by tomas-knap** [comment] 2015-10-09 09:41
Regarding the Deb packages, yes, please use Debian Wheezy 7, this was the environment we tested on.

**Comment by skarampatakis** [comment] 2015-10-09 11:10
Sorry for late response but since today morning I am trying to fix the installation with what you have suggested. So long:
1) I have uninstalled Java 8 and built plugins with java 7 from develop branch as suggested and loaded  perfectly.
2) I am trying to import the pipeline @jindrichmynarz sent to me. I had problem with l-rdfToFiles version since available version was only 2.1.4 but pipeline used 2.2.0-SNAPSHOT which is not available so i could not built to. The solution was to change the version of that particular plugin to what i had.
3) Pipeline could not loaded properly because of missing DPUs i had already deployed. Particular t-xslt which was reported as missing but I had it in the same version. Moreover I had another misssing DPU, l-ckan0dcz which i found in [this repo](https://github.com/mff-uk/DPUs) but could not install because of missing dependency on module-test:jar:1.6.0-SNAPSHOT

So I cant't import the pipeline. Currently I started set up a Debian wheezy 7.9 VM as suggested to see if this finally works without any problems. I will inform on any update and hope everything will be ok.

**Comment by tomas-knap** [comment] 2015-10-09 12:25
ad 2) In general it works in a way that you cannot and should not try to import plugin which points to newer major/minor version of API then your Core is using. So for example, you cannot import DPU which requires 2.2.X UV API to UV Core with API 2.1.X Before using such plugin, Core should be updated. 

ad 3) When using DPUs from other repos (not from the repository with Core plugins), such situations may happen. For which purpose do you need l-ckanOdcz? 

ad 3) The situation with t-xslt is a bit suspicious, if you can write it down as an issue to https://github.com/UnifiedViews/Plugins/issues, that would be great.

**Comment by skarampatakis** [comment] 2015-10-09 12:40
2) My Core version is 2.2.0 but I think is from master branch. Maybe should change to develop?
3) This is used by the pipeline @jindrichmynarz send to me in order to study the use of Unified Views in order to progress on our project. I think it uploads the dataset produced on local instance of CKAN. 
3) i will do so 

NEW 4) I set up Debian Wheezy 7.9 and followed the instructions provided to install directly from debian packages but i had problem with the instalation

```
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Reading task descriptions...
The following partially installed packages will be configured:
  unifiedviews-backend unifiedviews-backend-mysql unifiedviews-mysql 
  unifiedviews-webapp 
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
Writing extended state information...
Setting up unifiedviews-backend-mysql (2.2.0) ...
 >>> db_creadentials
 <<< db_creadentials
 >>> db_up
INFO: Waiting for mysql to be up...dpkg: error processing unifiedviews-backend-mysql (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of unifiedviews-backend:
 unifiedviews-backend depends on unifiedviews-backend-mysql (>> 2.2) | unifiedviews-backend-pgsql (>> 2.2); however:
  Package unifiedviews-backend-mysql is not configured yet.
  Package unifiedviews-backend-pgsql is not installed.

dpkg: error processing unifiedviews-backend (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of unifiedviews-webapp:
 unifiedviews-webapp depends on unifiedviews-backend (>> 2.2); however:
  Package unifiedviews-backend is not configured yet.
 unifiedviews-webapp depends on unifiedviews-backend (<< 2.3); however:
  Package unifiedviews-backend is not configured yet.

dpkg: error processing unifiedviews-webapp (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of unifiedviews-mysql:
 unifiedviews-mysql depends on unifiedviews-backend-mysql (>> 2.2); however:
  Package unifiedviews-backend-mysql is not configured yet.
 unifiedviews-mysql depends on unifiedviews-backend-mysql (<< 2.3); however:
  Package unifiedviews-backend-mysql is not configured yet.
 unifiedviews-mysql depends on unifiedviews-backend (>> 2.2); however:
  Package unifiedviews-backend is not configured yet.
 unifiedviews-mysql depends on unifiedviews-backend (<< 2.3); however:
  Package unifiedviews-backend is not configured yet.
 unifiedviews-mysql depends on unifiedviews-webapp (>> 2.2); however:
  Package unifiedviews-webapp is not configured yet.
 unifiedviews-mysql depends on unifiedviews-webapp (<< 2.3); however:
  Package unifiedviews-webapp is not configured yet.

dpkg: error processing unifiedviews-mysql (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 unifiedviews-backend-mysql
 unifiedviews-backend
 unifiedviews-webapp
 unifiedviews-mysql
Setting up unifiedviews-backend-mysql (2.2.0) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Reading task descriptions...
```

**Comment by jindrichmynarz** [comment] 2015-10-10 15:03
I'll try to fill in some missing points.

* l-rdfToFiles version 2.2.0-SNAPSHOT was compiled from the develop branch of /UnifiedViews/Plugins. As @tomas-knap explained, you need can't import a pipeline that uses a newer version of a DPU than the version of this DPU that you have installed. In order to import the pipeline, you need to update the DPU version. This can be done by either exporting the pipeline with JAR-files of DPUs and then imported via the DPU templates tab or just by compiling the develop version of the DPU and replacing the old version with it.
* l-ckanOdcz is used because we use UnifiedViews outside of the context of [OpenDataNode](http://opendatanode.org/), which is required for the COMSODE DPUs to work. Unlike @skarampatakis I'm able to compile l-ckanOdcz using the master branch of /mff-uk/DPUs repository. @tomas-knap, is it possible there is a problem with missing /UnifiedViews/Plugin-DevEnv?
* It seems to be that the import problems of t-xslt DPU indicate a bug.

**Comment by tomas-knap** [comment] 2015-10-12 08:28
Regarding l-ckanOdcz, the problem is that it requires certain outdated dependency - module-test in version 1.6 - see: https://github.com/mff-uk/DPUs/blob/master/dpu/l-ckanOdcz/pom.xml#L64-L69

So to fix this, please remove this dependency and skip tests of the DPU by calling "mvn clean install -DskipTests"

**Comment by tomas-knap** [comment] 2015-10-12 08:31
@skarampatakis, Regarding your issue with installation from Deb packages, it seems that it was not possible to start Mysql. Is there already a different Mysql process up and running? 

@Jan-Marcek may have further comments to the problems installing from Deb packages

**Comment by skarampatakis** [comment] 2015-10-12 10:37
I am currently trying to install everything from start on Debian Wheezy 7.9 VM using Java 8, cloning develop branches and hope everything is ok. I will inform with progress.
Regarding deb packages i had a fresh installation of Debian and installed just Unified Views, so mysql was not present before.

**Comment by Jan-Marcek** [comment] 2015-10-12 11:19
@skarampatakis 
please use 
```
apt-get install unifiedviews-pgsql
```

This debian package we are using at http://opendatanode.org/. (it is used frequently - tested frequently )
The difference between ```unifiedviews-pgsql``` and ```unifiedview-mysql``` is only in what database engine is used. Fortunately, ```unifiedview-mysql``` has got some issue. Thank you for reporting.

**Comment by jindrichmynarz** [comment] 2015-10-12 12:25
Maybe the outdated dependency in l-ckanOdcz can be removed directly by the DPU's maintainer @jakubklimek.

**Comment by skarampatakis** [comment] 2015-10-22 16:33
Hi all, I am sorry for the delay but had a lot of work to do So, I am currently working with unified views version 2.2.0 as was build from source on my 15.04 Lubuntu installation using java 7. Have not time for now to try the postgre installation. Many of the plugins are working, some of them need special treatme nt such as creating the folder in Core/target/dpu and move the appropriate jar.

**Comment by tomas-knap** [comment] 2015-10-27 08:26
Ok, great.  Manual creation of folders in Core/target/dpu is very strange, it works in a way that new DPUs should be imported via administration interface of UV and they are automatically placed to Core/target/dpu. Are the permissions for that folder correctly set - has frontend (tomcat) write access to that folder to create new DPUs?

**Comment by tomas-knap** [comment] 2015-11-02 19:46
@skarampatakis Should I close this thread? Or do you still have any related issue?

**Closed** 2015-11-13 15:59 UTC
Labels: priority: Normal, severity: question, status: needs discussion
